### ISSUE TITLE
How do I set reactions on an send message?

### ISSUE THREAD

**Issue by Promotheux** [CharlotteDunois/Yasmin#101]
I'm trying to rebuild my nodeJS bot to PHP, because I do like PHP more. Now I got my poll option and I want to add reactions to it. But how do I get my sended message to add the reactions? 

This is my code:
`       $embed = new \CharlotteDunois\Yasmin\Models\MessageEmbed();
            $embed 
                ->setTitle('Er is een poll gestart!')
                ->setColor(rand(0, 16777215))
                ->addField('De vraag is als volgt:', "De vraag")
                ->setTimestamp();

            return $context->channel->send('', ['embed' => $embed]);`

**Comment by JABirchall** [comment]
```php
$context->channel->send('', ['embed' => $embed])->then(function(Message $message) {
    $message->collectReactions();
});
```

[Message@collectReactions](https://yasmin.neko.run/master/CharlotteDunois/Yasmin/Models/Message.html#method_collectReactions)

**Comment by Promotheux** [comment]
Thanks! But the collectReactions() needs an $filter parameter, I don't know what exactly has to be given as parameter. Found this in the docs: "The filter to only collect desired reactions. Signature: function (MessageReaction $messageReaction, User $user): bool"

**Comment by sylae** [comment]
To add a react to the message, allowing users to click:
```php
$message->channel->send("React with `:eye:` or `:eyes:` to vote.")->then(function ($newMessage) {
    $promises = [];
    $promises[] = $newMessage->react("👁");
    $promises[] = $newMessage->react("👀");
    
    return \React\Promise\all($promises)->then(function (array $results) use ($newMessage) {
        return $newMessage->channel->send("reacts added!");
    });
});
```

To get all the reacts for vote tallying or whatever, you can use the following code:
```php
return \React\Promise\all($message->reactions->map(function (\CharlotteDunois\Yasmin\Models\MessageReaction $mr) {
    return $mr->fetchUsers();
})->all())->then(function (array $reactUsers) use ($message) {

    /** @var \CharlotteDunois\Collect\Collection  $users */
    foreach ($reactUsers as $reactionID => $users) {

        // if choosing multiple options is okay, just do $users->count()-1;
        // Otherwise, you can iterate...

        /** @var \CharlotteDunois\Yasmin\Models\User  $user */
        foreach ($users as $user) {
            // here we have each user who reacted with that particular react.
            // do math or whatever
        }
    }
});
```

If you're using `collectReactions()` and want everything, you can probably just use this as the callback:
```php
function (MessageReaction $messageReaction, User $user): bool {
    return $messageReaction->message->id == 12345; // your message id from wherever. Sanity check.
}
```

**Comment by CharlotteDunois** [comment]
> If you're using `collectReactions()` and want everything, you can probably just use this as the callback:
> 
> ```
> function (MessageReaction $messageReaction, User $user): bool {
>     return $messageReaction->message->id == 12345; // your message id from wherever. Sanity check.
> }
> ```

Not quite correct. The reactions are already filtered by the message, so all you'd need to do would be `return true`.
https://github.com/CharlotteDunois/Yasmin/blob/7c38faf5784b4bffbe0560931ebf43cc6fa10044/src/Models/Message.php#L299-L301
