### ISSUE TITLE
Client->getPing() always returns NAN

### ISSUE THREAD

**Issue by JackMD** [CharlotteDunois/Yasmin#105]
**Please describe the issue you are having:**
Trying to get the ping of the client always returns`NAN`.

**If you are encountering any errors, post the full stack trace here:**
```
NONE
```

**Please include a Minimal, Complete and Verifiable Example:**
```php
$client = new Client([], $loop);

$client->on("message", function(Message $message) use ($client): void{
   if($message === "ping"){
      $message->reply("Pong. Latency: " . $message->client->getPing();
      var_dump($message->client->getPing(), $client->getPing());
   }
}
```

**Please include the expected output of the MCVE:**
```php
Expected to return ping (int|float)
```

**Please include the actual output of the MCVE:**
```php
Always returns NAN
```

**Further details:**

- Yasmin version: 0.6.0
- PHP version: 7.2
- Operating System: Windows 10

- [ ] I have also tested the issue on latest master with commit hash:

**Comment by CharlotteDunois** [comment]
Technically `NAN` is a float. :)

But I know what you're playing at. The ping comes from the regular heartbeats we are doing. The first heartbeat is done after approx. 43 seconds after getting an authenticated gateway connection. And this will repeat every ~43 seconds.

So the method will return `NAN` as long as we haven't done a single heartbeat. So you need to wait ~45 seconds before you can get the first ping.

**Comment by JackMD** [comment]
Alright that solves it. Thank you
