### ISSUE TITLE
Adding a role to a user when receiving a message

### ISSUE THREAD

**Issue by joelwmale** [CharlotteDunois/Yasmin#110]
I'm trying to add a role to a user once they send my bot a specific command. I'm currently not having any errors, but it is never calling my reply saying it has added the role. I also could not find a clean way to get access to the guild member, so the way I've done it is a bit disgusting.

```
$rawMemberArray = json_decode(json_encode($message->__get('member')), true);
$member = [
    'user' => $rawMemberArray,
];

$guildMember = new \CharlotteDunois\Yasmin\Models\GuildMember($this->client, $message->__get('guild'), $member);
$guildMember->addRole('583686377992880167')->done(
    function () use ($message) {
        $message->reply('I have successfully synced your character and updated your roles.');
    },
    function($error) {
        throw new \Exception($error);
    }
);
```

Any ideas?

**Comment by CharlotteDunois** [comment]
My idea is that you've did everything wrong there. If the constructor is **not** documented, then the constructor is internal only (it means it's not safe for use). The `$member` array does not even have the correct format.

What is wrong with the `GuildMember` from `$message->member`? It returns the `GuildMember` or `null` (= uncached, should never or rarely be the case).

```php
$member = $message->member;

$member->addRole('583686377992880167')->done(
    function () use ($message) {
        $message->reply('I have successfully synced your character and updated your roles.');
    },
    function($error) {
        throw new \Exception($error);
    }
);
```

**Comment by joelwmale** [comment]
Hmm, sorry - I see now you have an `@internal` docblock on the GuildMember constructor. 

I did try your version and got nothing. I've got the role id by sending @role in discord and copying the id, and it does hit that addRole code, but just doesn't do anything after that.

It doesn't log anything or proceed into the callbacks, nor does it add the role to the user. It also doesn't throw any errors. Any ideas?

**Comment by CharlotteDunois** [comment]
Rightclicking the mention and clicking on copy id does NOT copy the role id. It copies the message id (blame discord).

However it should always give you an error, regardless of the ID. Does the process exit? Does anything happen at all? 

You can listen on the `debug` event and print the message to stdout to see what is going on. Additionally there is an `error` event, also attach a listener there and print it to stderr/stdout.
This will give you more insight into what is happening inside the library.

**Comment by joelwmale** [comment]
Yeah sorry, I actually ran `\@member` to get the role id. 

It seems my throw exception was not working (or being caught within the enclosing try/catch. The error is actually missing permissions, which is interesting. The bot role has Admin Server, Manage Roles, and all admin permissions, and the bot actually has that role.

**Comment by joelwmale** [comment]
Followed this: https://github.com/y21/discordcaptcha/wiki/DiscordAPIError-50013-Missing-Permissions and got it fixed. Turns out role permission matters more then I thought.

Thanks mate for your help!
