### ISSUE TITLE
TextChannel fetchMessages

### ISSUE THREAD

**Issue by janvernieuwe** [CharlotteDunois/Yasmin#119]
**Please describe the issue you are having:**
In v0.5 i used channel->fetchMessages alot, this does not seem to work anymore since v6

**If you are encountering any errors, post the full stack trace here:**
```
No error is generated, the callback is never called

```

**Please include a Minimal, Complete and Verifiable Example:**
```php
        $channel->fetchMessages()->done([$this, 'onMessagesLoaded']);
    }

    /**
     * @param Collection $messages
     */
    public function onMessagesLoaded(Collection $messages): void
```
Is what I used and worked in v0.5.* but not in v0.6.*

**Please include the expected output of the MCVE:**
n/a

**Please include the actual output of the MCVE:**
n/a
**Further details:**

- Yasmin version: 0.6.1
- PHP version: 7.3.6
- Operating System: Ubuntu / whatever heroku is running

- [ /] I have also tested the issue on latest master with commit hash: b8a164282aafd5a004b5399781456b7aaa70fbaa

Thanks you much for providing this lib @CharlotteDunois .
If you need any more info's don't hesitate to ping me!

**Comment by CharlotteDunois** [comment]
Between v0.5 and v0.6 has nothing changed for `fetchMessages`. Errors end up in the promise rejection handler, you don't have a promise rejection handler and even though the `done` method should be throwing, I've sometimes seen no exception being thrown. So to make absolutely sure that there's no promise rejection, you can add a promise rejection handler (second argument of `done`).

And as side note: Heroku is not meant to be used as host for bots (it's meant for websites and APIs), so you should consider relocating to a better host for various reasons.

**Comment by janvernieuwe** [comment]
Thanks for the advise, I'll add the rejection code and also ordered a real VPS to deploy on.
