### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Zedstar16** [CharlotteDunois/Yasmin#125]
How can i use functions from other classes in my bot files and allow the bot to recognise the existence of these classes

**Comment by CharlotteDunois** [comment]
This entirely depends on your code. Yasmin does only interact with the Discord API, how your bot does all the logic, loads all code and knows about all the classes is up to you.

I'd recommend you to first get deeper into PHP itself, before trying to create a bot with PHP. It's a complex process and requires fundamental understanding. As this is not a Yasmin question, I'll close this issue.
