### ISSUE TITLE
How to send many messages to DM by user ID?

### ISSUE THREAD

**Issue by Nereg** [CharlotteDunois/Yasmin#132]
Hello ! I have one problem. I need to send notifications to users. I have DB with their ID's in discord. What way is the best? I don't know how to send messages to users by their ID's !

**Comment by CharlotteDunois** [comment]
You need to fetch the user ([`Client::fetchUser()`](https://yasmin.neko.run/v0.6.1/CharlotteDunois/Yasmin/Client.html#method_fetchUser)), open a DM channel ([`User::createDM()`](https://yasmin.neko.run/v0.6.1/CharlotteDunois/Yasmin/Models/User.html#method_createDM)) and then send the message through the channel ([`TextChannelInterface::send()`](https://yasmin.neko.run/v0.6.1/CharlotteDunois/Yasmin/Interfaces/TextChannelInterface.html#method_send)).

**Comment by Nereg** [comment]
Thank you for your help! I will try this soon.

**Comment by Nereg** [comment]
Yeah it's working !

**Comment by Nereg** [comment]
Yeah it's working !
