### ISSUE TITLE
FetchMessages() returns blank or error

### ISSUE THREAD

**Issue by BigBoyGaz** [CharlotteDunois/Yasmin#142]
Hi, 

I'm trying to fetch a Message from an ID that I have stored in a database. However, I cannot seem to actually fetch the message. Looked all over the documentation and could not work it out. 

![image](https://user-images.githubusercontent.com/58340215/69882731-1350a480-12c9-11ea-9cd6-59010a797962.png)

That's what I keep getting whenever trying... please help :)

**Comment by CharlotteDunois** [comment]
See this tutorial: https://sergeyzhuk.me/2017/06/16/phpreact-promises/
