### ISSUE TITLE
Follow PSR-2

### ISSUE THREAD

**Issue by aequasi** [CharlotteDunois/Yasmin#38]
Common standard in PHP is to follow the PSR-2 guidelines.

http://www.php-fig.org/psr/psr-2/

**Comment by CharlotteDunois** [comment]
That may be so, but I think there are some rules which are completely out of mind. I know the common thing in PHP is to just follow it anyway, but I can't do that if I don't completely stand behind it.

**Comment by aequasi** [comment]
Its easy enough to follow. Especially when using something like styleci

**Comment by CharlotteDunois** [comment]
I think you didn't get my point, so I'll try an analogy. Would you sit into a visibly broken down car, which doesn't guarantee your safety, just because it's easy to get into it? Probably not. It's about the same with the PSR. I won't jump on the PSR train just because "it's easy to follow" and there are automated scripts which apply the PSR guidelines.

**Comment by aequasi** [comment]
I dont think you get the point of following a PSR. It's done so that others can easily read and contribute to your code, which is very important in the open source community. Trying to go through your code, and I'm finding a bunch of things that are confusing. Primarily, the lack of visibility on your methods. They all seem to be private, but PHP's default visibility is public.

On top of making your code easier to follow and contribute to, following PSR's also make your code less prone to errors and bugs.

This isnt an attack on your coding stile, but an opportunity for you to engage with the community in a beneficial way. If you want to just close this and not think about it, so be it, but that would be unfortunate.

**Comment by CharlotteDunois** [comment]
That some methods are public but seem to be private are because these are internal methods which need to be accessed from other parts of the internal workings. Making them private wouldn't make that possible. 

These are marked with the phpdoc tag `@internal`.
