### ISSUE TITLE
Update React/EventLoop

### ISSUE THREAD

**Issue by DevNatan** [CharlotteDunois/Yasmin#56]
Hello, I'm using this library for Discord bots in PHP, but I had a "problem" while trying to install.
I already had React / EventLoop installed in the last version and even then at the time of installing it said that the version was outdated.

An image:
![image](https://user-images.githubusercontent.com/24600258/43526441-9cf4ccc0-957a-11e8-9c72-2a5ca9a41e21.png)

**Comment by CharlotteDunois** [comment]
Version 0.4.1 indeed does require `0.4.3` in the composer.json, but there is already a [commit](https://github.com/CharlotteDunois/Yasmin/commit/cc895779e5cdc4c4ee904244a0bdfe60ddc633d6) in master which fixes this.

As such the next release will (officially) work with the latest version.
