### ISSUE TITLE
Swoole support

### ISSUE THREAD

**Issue by Jurigag** [CharlotteDunois/Yasmin#77]
**Describe the solution you'd like**
I see you use loop from react, you could possibly provide client to use one with swoole.

**Describe alternatives you've considered**

**Additional context**
More about swoole - https://github.com/swoole/swoole-src

**Comment by CharlotteDunois** [comment]
Thank you for filing this issue!

Unfortunately it's not as easy as just simply replacing the client. Under the hood more must be done. The HTTP and websocket part need work too. The client just takes the client and distributes it. The only thing the client really uses from the event loop is providing auto destroying timers as soon as the client gets destroyed.

While I do think Swoole is a great native alternative to ReactPHP, I think it's out of scope of this project to provide additional alternative implementations. ReactPHP really just works out of the box while Swoole requires compiling the extension (on Windows not even easy and Cygwin isn't that great either).

But if you really require or want to use Swoole, you can extend the parts yourself and replace the ReactPHP components with Swoole equivalents. The current client already allows to explicitely pass a `WSManager` and `APIManager` into the client (they just need to extend the Yasmin classes, to ensure the  methods exist, but aside from that you can replace all the existing methods - if required).

https://github.com/CharlotteDunois/Yasmin/blob/91ab40d63c823cf5a0d38b8c2175bfb2fbec127a/src/Client.php#L252-L261

https://github.com/CharlotteDunois/Yasmin/blob/91ab40d63c823cf5a0d38b8c2175bfb2fbec127a/src/Client.php#L266-L275

For HTTP requests `clue/buzz-react` is used (only master branch and future v0.6 - current and previous relases use guzzle), but if you don't use that client yourself, you can simply create a class in the same namespace (so the original package doesn't get autoloaded) that uses Swoole, so in the end even though it doesn't explicitely use Swoole, it uses your class which delegates it away to Swoole.

See [`clue/buzz-reactphp`](https://github.com/clue/reactphp-buzz) and
https://github.com/CharlotteDunois/Yasmin/blob/91ab40d63c823cf5a0d38b8c2175bfb2fbec127a/src/Utils/URLHelpers.php#L58

If you ever get to a working project and upload it to GitHub, I'd be happy to link to it in the readme!
