### ISSUE TITLE
Bot Crashing with errors.

### ISSUE THREAD

**Issue by Thurston00** [CharlotteDunois/Yasmin#79]
**Please describe the issue you are having:**
The bot stays alive for around 30 minutes before giving the ```PHP Warning: Illegal string offset 'id'``` error. After it does that once, it does it again a few minutes later then just completely crashes. I am running a loop every 600 seconds ```addPeriodicTimer(600, [$this, 'modupdate'])```, but that doesn't seem to be the issue here. The issue seems to be relating to the "patch()" function, which I'm not using. No functions/commands are being ran besides the timer, so that seems like the only "relevant" part.

Forgive me if my knowledge is a bit... off, and let me know if you require more details!

**If you are encountering any errors, post the full stack trace here:**
```
PHP Warning:  Illegal string offset 'id' in /root/thurston/discord/vendor/charlottedunois/yasmin/src/Models/GuildMemberStorage.php on line 104
PHP Warning:  Illegal string offset 'id' in /root/thurston/discord/vendor/charlottedunois/yasmin/src/Models/GuildMember.php on line 122
PHP Warning:  Illegal string offset 'id' in /root/thurston/discord/vendor/charlottedunois/yasmin/src/Models/GuildMemberStorage.php on line 104
PHP Warning:  Illegal string offset 'id' in /root/thurston/discord/vendor/charlottedunois/yasmin/src/Models/GuildMember.php on line 122
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to CharlotteDunois\Yasmin\Models\UserStorage::patch() must be of the type array, string given, called in /root/thurston/discord/vendor/charlottedunois/yasmin/src/Models/GuildMember.php on line 123 and defined in /root/thurston/discord/vendor/charlottedunois/yasmin/src/Models/UserStorage.php:67
Stack trace:
#0 /root/thurston/discord/vendor/charlottedunois/yasmin/src/Models/GuildMember.php(123): CharlotteDunois\Yasmin\Models\UserStorage->patch('290920632512937...')
#1 /root/thurston/discord/vendor/charlottedunois/yasmin/src/Models/GuildMemberStorage.php(110): CharlotteDunois\Yasmin\Models\GuildMember->__construct(Object(CharlotteDunois\Yasmin\Client), Object(CharlotteDunois\Yasmin\Models\Guild), Array)
#2 /root/thurston/discord/vendor/charlottedunois/yasmin/src/Models/Guild.php(1200): CharlotteDunois\Yasmin\Models\GuildMemberStorage->factory(Array)
#3 /root/thurston/discord/vendor/charlottedunois/yasmin/src/WebSocket/Events/TypingStart.php(42): CharlotteDunois\Yasmin\Models in /root/thurston/discord/vendor/charlottedunois/yasmin/src/Models/UserStorage.php on line 67
```

**Further details:**

- Yasmin version: v0.5.1
- PHP version: 7.1.24
- Operating System: Ubuntu 16.04

**Comment by CharlotteDunois** [comment]
Sorry, I wasn't able to see the issue yesterday (GitHub said it doesnt exist).

That's indeed a bug that exists in v0.5.1, but is fixed in master. If you don't need typing events, you can work around this bug by disabling the websocket event `TYPING_START` through the yasmin client options (refer to the documentation.

Once clue releases a new version of reactphp-buzz I can release a new version.
