### ISSUE TITLE
Incorrect clue/buzz-react version

### ISSUE THREAD

**Issue by arcdigital** [CharlotteDunois/Yasmin#86]
**Please describe the issue you are having:**
On master, you reference clue/buzz-react 2.5.1, but that version doesn't exist. The latest version available is 2.5.0.

https://github.com/clue/reactphp-buzz/releases

**Comment by CharlotteDunois** [comment]
I'm still waiting for a critical patch release by clue. That's why I already set it to 2.5.1. Because this librrary does not work with 2.5.0. See #75.
