### ISSUE TITLE
fetchMessage on guild channel not resolving

### ISSUE THREAD

**Issue by AdamHebby** [CharlotteDunois/Yasmin#96]
**Please describe the issue you are having:**
Cannot successfully call `fetchMessage` on guild TextChannel. I store a Guild ID, Channel ID and Message ID for the bot to later fetch and collect reactions on, except fetchMessage does not call any functions passed or log any errors. All ID's are 100% correct, I have validated that they are correct. The guild and channel are successfully fetched.

I have turned off messageCache to reduce memory usage and increase speed, but turning this back on has no effect.

**Please include a Minimal, Complete and Verifiable Example:**
```php
    $guild     = $this->client->guilds->get($guildId);
    $channel   = $guild->channels->get($channelId);

    $channel->fetchMessage($messageId)->done(
        function (Message $message) {
            var_dump($message);
        },
        function ($error) {
            var_dump($error);
        }
    );
```

**Please include the expected output of the MCVE:**
```php
class CharlotteDunois\Yasmin\Models\Message#280 (30) {
    ... // Message instance
}
```

**Please include the actual output of the MCVE:**
```php
// nothing :/
```

**Further details:**
The bot's repo is private.

- Yasmin version: 0.5.1
- PHP version: PHP 7.2.15-0ubuntu0.18.04.1 (cli)
- Operating System:  Ubuntu 18.04.1 LTS (Linux Subsystem for Windows 10)

- [x] I have also tested the issue on latest master with commit hash: 1534b4e
Latest commit gives me an error: 
```
[2019-04-07 23:35:39] MyBot.ERROR (MyBot\Runner: 198): Exception caught {"exception":"[object] (Error(code: 0): Call to a member function close() on null at ./vendor/charlottedunois/yasmin/src/WebSocket/WSConnection.php:633)
[stacktrace]
#0 ./vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): CharlotteDunois\\Yasmin\\WebSocket\\WSConnection->CharlotteDunois\\Yasmin\\WebSocket\\{closure}('\\x02\\x86,P* \\xC85\\xD8\\xD5\\xCF\\xD95>4...', Object(Ratchet\\Client\\WebSocket))
#1 ./vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\\Client\\WebSocket->emit('message', Array)
#2 ./vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(104): Ratchet\\Client\\WebSocket->Ratchet\\Client\\{closure}(Object(Ratchet\\RFC6455\\Messaging\\Message))
#3 ./vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(60): Ratchet\\RFC6455\\Messaging\\MessageBuffer->processData('\\x82~\\x00\\xBD\\x02\\x86,P* \\xC85\\xD8\\xD5\\xCF...')
#4 ./vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Ratchet\\RFC6455\\Messaging\\MessageBuffer->onData('\\x82~\\x00\\xBD\\x02\\x86,P* \\xC85\\xD8\\xD5\\xCF...')
#5 ./vendor/react/stream/src/Util.php(71): Evenement\\EventEmitter->emit('data', Array)
#6 ./vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\\Stream\\Util::React\\Stream\\{closure}('\\x9C\\x87\\xD5\\xB8\\e\\x85\\x07\\x8C\\xAE\\x15\\x1DE\\x8A\\x82,...')
#7 ./vendor/react/stream/src/DuplexResourceStream.php(193): Evenement\\EventEmitter->emit('data', Array)
#8 ./vendor/react/event-loop/src/StreamSelectLoop.php(244): React\\Stream\\DuplexResourceStream->handleData(Resource id #307)
#9 ./vendor/react/event-loop/src/StreamSelectLoop.php(211): React\\EventLoop\\StreamSelectLoop->waitForStreamActivity(15917025)
#10 ./src/MyBot/Runner.php(196): React\\EventLoop\\StreamSelectLoop->run()
#11 ./bin/cron-runner.php(30): MyBot\\Runner->cronRunEventNotifier()
#12 {main}
"} 
```

**Comment by CharlotteDunois** [comment]
The message cache has no effect on the performance. Calls to the message cache are still made, but they're no-op.

When exactly do you call `fetchMessage`? I can't reproduce your issue, so it would probably be useful to know when you call it and what happens (write `debug` event to stdout and post the output).

PS: The latest master error is something I've never seen before, but it indicates that the websocket connection was closed before the message was fully received and thus zlib was unable to fully decode it.

**Comment by AdamHebby** [comment]
So I call fetch message after all the setup, then fetch events from the DB, I iterate over each event then do what I posted above. I don't want to make my post open source, but I could add you as a collaborator if that would help?

Anyway, here's the setup:
```php
// Build the react loop so we have the promise
$this->reactLoop = ReactLoop::create();
$this->discordClient = new DiscordClient(array(
    'ws.presenceUpdate.ignoreUnknownUsers' => true,
    'fetchAllMembers'   => false,
    'messageCache'      => false,
    'presenceCache'     => false,
    'ws.disabledEvents' => array(
        'TYPING_START',
        'CHANNEL_PINS_UPDATE',
        'GUILD_BAN_ADD',
        'GUILD_BAN_REMOVE',
        'GUILD_EMOJIS_UPDATE',
        'GUILD_INTEGRATIONS_UPDATE',
        'GUILD_MEMBER_ADD',
        'GUILD_MEMBER_UPDATE',
        'GUILD_MEMBER_REMOVE',
        'GUILD_ROLE_CREATE',
        'GUILD_ROLE_UPDATE',
        'GUILD_ROLE_DELETE',
        'MESSAGE_REACTION_ADD',
        'MESSAGE_REACTION_REMOVE',
        'MESSAGE_REACTION_REMOVE_ALL',
        'VOICE_STATE_UPDATE',
        'VOICE_SERVER_UPDATE'
    )
), $this->reactLoop);

$this->discordClient->on('ready', function () {
    $this->connectToDatabase();
    $this->taskHandler->runEventNotifier($this->discordClient);
    $this->discordClient->destroy();
});

$this->discordClient->on('debug', function ($string) {
    echo $string . "\n";
});

$this->discordClient->login(getenv('BOT_TOKEN'));

try {
    $this->reactLoop->run();
} catch (\Throwable $e) {
    $this->logger->addError('Exception caught', array('exception' => $e));
}
```

cronTaskHandler::runEventNotifier
```php
$timeout = (new Carbon('now', 'UTC'))->addMinutes(60 * 10);

$this->client->on('error', function (\Throwable $message) {
    $this->logger->addError($message->getMessage());
});

echo "$timeout \n";

$events = $this->eventManager->fetchEventsInNext("$timeout");

foreach ($events as $event) {
    $messageId = $event->notifyId;
    $guildId   = $event->guildId;
    $channelId = $event->channelId;

    $guild     = $this->client->guilds->get($guildId);
    $channel   = $guild->channels->get($channelId);

    $channel->fetchMessage($messageId)->done(
        function (Message $message) {
            echo "nothing on done \n";
            var_dump($message);
        },
        function ($error) {
            echo "nothing on error \n";
            var_dump($error);
        }
    );
}
```

Debug output:
```
Shard 0 using compress context ZlibStream
Shard 0 connecting to WS wss://gateway.discord.gg/?v=6&encoding=json&compress=zlib-stream
Shard 0 initialized compress context for shard
Shard 0 connected to WS
Shard 0 connected to Gateway via gateway-prd-main-c056
Shard 0 sending IDENTIFY packet to WS
Shard 0 sending WS packet with OP code 2
2019-04-09 06:23:50
Adding request "channels/533384855459725312/messages/564888726178889789" to ratelimit bucket
Adding request "channels/533384855459725312/messages/564888740430872576" to ratelimit bucket
Adding request "channels/533384855459725312/messages/564888705081540618" to ratelimit bucket
Adding request "channels/533384855459725312/messages/564888710370295839" to ratelimit bucket
Adding request "channels/533384855459725312/messages/564888755387760644" to ratelimit bucket
Adding request "channels/533384855459725312/messages/564888774975422504" to ratelimit bucket
Shard 0 disconnecting from WS
Shard 0 destroyed compress context
Shard 0 disconnected with code 1000 and reason ""
```

PS.With the latter error, I had no idea what was going on, I barely understand the core of how Yasmin works but it was interesting reading the issue. FYI this debug output is from the latest release, I reverted after I posted the last issue

**Comment by CharlotteDunois** [comment]
It doesn't work because you call `$this->discordClient->destroy();` in the ready event. :)
I don't see why you call `destroy`, because that actively closes the gateway connection and clears all HTTP requests.

If you don't need a gateway connection, you should probably use restcord instead.

**Comment by AdamHebby** [comment]
I'm actually annoyed at myself :/ Such a rookie move, of course that would happen!

Thank you very much!

FYI, this was a smaller part of a much larger bot, and the code that you saw was the start of a long command.

P.S I love your work! It's by far the best PHP Discord API Library out there. My only gripe is that there aren't many examples so one is forced to trawl through the source code. I might add some examples if that's okay?

Also what was the reasoning behind removing getType of a TextChannel? What's the alternative?

**Comment by CharlotteDunois** [comment]
The reasoning is that a string is much more open to mistakes than interfaces, so checking the interface is the new way, for that reason I've added new concrete interfaces you can check against.

But I'm wondering if I should still keep type, but as integer (just like in the Discord API). But I'm not sure of that yet.
